services:
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "8005:8001"
    depends_on:
      postgres:
        condition: service_healthy 
    env_file:
      - ./services/auth-service/.env

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 281205
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  article-service:
    build: ./services/article-service
    container_name: article-service
    ports:
      - "8006:8002"
    depends_on:
      - mongodb
    env_file:
      - ./services/article-service/.env

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  gateway-service:
    build: ./services/gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
    - AUTH_SERVICE_URL=http://auth-service:8001
    - ARTICLE_SERVICE_URL=http://article-service:8002
    - JWT_SECRET=supersecret
    depends_on:
    - auth-service
    - article-service